apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argo-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/deepakkumar07-debug/argo-cd-learnings.git
    targetRevision: HEAD # always the last commit
    path: argocd-app-config/dev
  destination:
    server: https://kubernetes.default.svc # internal service name for k8s api server
    namespace: myapp # which namespace argocd will apply the changes from git repo (i.e) apply to myapp namespace

  # if not myapp namespace exists in cluster
  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    #  enable automatic track and sync
    # this automate attribute will configure argoCD to pull the changes in every 3 minutes,
    # if we dont want this dealy, we can configure a Git webhook integration between git repo and argocd.
    automated:
      # enable automatic self-healing
      selfHeal: true # undo or overwrites any manual changes with the git repository state instead.
      # enable automatic pruning, by default, automatic sync will not delete resources(deleting deployment,service)
      prune: true
